sonar.projectKey=hina-beauty-glow
sonar.projectName=Hina Beauty Glow
sonar.sources=client/src,server/src,shared/src
sonar.tests=server/test,client/src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**
